### ISSUE TITLE
Webpage not available

### ISSUE THREAD

**Issue by dano2** [arvindr21/mediaPlayerApp#1]
Thanks for the mediaPlayerApp! A couple things...

1) I was getting an error, so I had to run "cordova plugin add com.ionic.keyboard"

2) While this worked in the GenyMotion emulator, when I try to run it on my android device, I instantly get a "Webpage not available" browser error. Could this have something to do with the src value that is set in the platforms config.xml file which contains the following line? It's trying to go that src URL on my mobile. Should it? I don't know how to fix this.
&lt;content original-src="index.html" src="http://192.168.56.1:8101"&gt;

Any suggestions?

Thanks again.

**Comment by arvindr21** [comment]
Please check : http://thejackalofjavascript.com/ionic-framework-cordova-and-file-api-a-media-player-app/#comment-1953783407

**Comment by dano2** [comment]
I'm still having a hard time getting this to actually work on my phone. Was going give feedback once I got it working. After the splash screen, I'm just getting "emptiness". That's the only way I can describe it. Again, it works fine in GenyMotion. When I run "ionic run android", for whatever reason, "src='http://192.168.56.1:8101'" ends up back in the config file. I don't know why or if that's even the problem. I'm not even able to get the broken web page any more. It's just blank. I have to look into how to debug while running from the device.

Thanks.

**Comment by arvindr21** [comment]
Okay, can you try cloning this repo as-is and then executing `ionic run android`?

**Comment by dano2** [comment]
Hi. Actually I finally got the app to load. For some reason the flag for livereload was breaking something. As for the app - the audio appears to be working well. However when clicking on the video (mp4) file, sometimes nothing will happen, and sometimes it will correctly prompt me to select a player. "adb logcat" displays the following when it doesn't work. Also, it seems the video will never work unless I run an audio file first.

I/chromium(21002): [INFO:CONSOLE(19532)] "TypeError: Object #<Scope> has no method 'stopAudio'
I/chromium(21002):     at Scope.$scope.showSubDirs (file:///android_asset/www/js/controllers.js:61:22)
I/chromium(21002):     at $parseFunctionCall (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:20270:18)
I/chromium(21002):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:52468:9
I/chromium(21002):     at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22326:28)
I/chromium(21002):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22425:23)
I/chromium(21002):     at HTMLUnknownElement.<anonymous> (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:52467:13)
I/chromium(21002):     at HTMLUnknownElement.eventHandler (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:10939:21)
I/chromium(21002):     at triggerMouseEvent (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2856:7)
I/chromium(21002):     at tapClick (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2845:3)
I/chromium(21002):     at HTMLDocument.tapTouchEnd (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:2963:5)", source:

My Setup:
OS: Mac OS X Yosemite
Node Version: v0.12.0
Cordova CLI: 4.3.0
Ionic CLI Version: 1.3.19
Xcode version: 6.2 (6C131e)
ios-sim version: 3.1.1
ios-deploy version: 1.4.0

-Edited

**Comment by arvindr21** [comment]
If you see [line 61 controllers.js](https://github.com/arvindr21/mediaPlayerApp/blob/master/mediaPlayerApp/www/js/controllers.js#L61) we are calling the method on [line 94 controllers.js](https://github.com/arvindr21/mediaPlayerApp/blob/master/mediaPlayerApp/www/js/controllers.js#L94). This method does not seem to in scope for some reason. 

You can use [chrome://inspect](https://developer.chrome.com/devtools/docs/remote-debugging), set a break point and see why this fails.

**Comment by dano2** [comment]
Man, I'm lovin chrome://inspect. Thanks for that tip. It's erroring because line 61 is calling the method before it has been attached to the scope, which is on line 94, which only occurs if a non-mp4 file has been selected. So, we just first need to check that the method exists. I replaced line 61 with the following and it worked nicely.

$scope.stopAudio && $scope.stopAudio();

I'm not sure how git works yet to make the change myself.

**Comment by arvindr21** [comment]
Cool!
